name: Clone workflow
on:
 workflow_dispatch:
  inputs:
    ENVIRONMENT:
      type: choice
      description: select target environment
      options: [DEV, ST, SIT, UAT, PROD, DR]

jobs:
  create-tar:
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repository
      run: |
       git clone https://github.com/OWNER/REPO.git
       env:
        GIT_ASKPASS: /bin/echo
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}    
    
    - name: List contents of GITHUB_WORKSPACE
      run: |
       echo "Listing contents of $GITHUB_WORKSPACE:"
       ls -la $GITHUB_WORKSPACE
