name: Clone and Upload workflow
on:
 workflow_dispatch:
  inputs:
    ENVIRONMENT:
      type: choice
      description: select target environment
      options: [DEV, ST, SIT, UAT, PROD, DR]

jobs:
  create-tar:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        repository: venuakula-bigdata/develop
        path: developtar
        token: ${{ secrets.ACTIONS_PAT }}
    - name: remove .git folder
      run: rm -rf developtar/.git
    - name: Create tar archive
      run: tar -czvf my-artifact.tar.gz developtar/
      working-directory: ${{ github.workspace }}
    - name: Untar the archive
      run: |
       tar -xzf ${{ github.workspace }}/my-artifact.tar.gz -C /
    - name: List contents of GITHUB_WORKSPACE
      run: |
       echo "Listing contents of $GITHUB_WORKSPACE:"
       ls -la $GITHUB_WORKSPACE
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Upload tar file to S3
      run: aws s3 cp ${{ github.workspace }}/my-artifact.tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/
