name: k8s workflow with token
on:
 workflow_dispatch:
  inputs:
    ENVIRONMENT:
      type: choice
      description: select target environment
      options: [DEV, ST, SIT, UAT, PROD, DR]

jobs:
  deploying-to-k8s:
    runs-on: self-hosted

    steps:
    - name: Clone private repository
      run: |
       cd ..
       git clone https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/venuakula-bigdata/develop.git
       pwd
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
          version: 'latest'
    - name: Setup kubeconfig
      run: |
       echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig.yaml
       pwd
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
    - name: Test Kubeconfig
      run: kubectl get nodes
      # run: kubectl --kubeconfig=/home/ubuntu/actions-runner/_work/devops-repo/devops-repo/kubeconfig.yaml get nodes
    - name: deploying to k8s
      run: |
       ls -la $GITHUB_WORKSPACE
       ls -la /home/runner/work/devops-repo
       ls -la /home/runner/work/devops-repo/develop
       kubectl --kubeconfig=kubeconfig.yaml -f /home/runner/work/devops-repo/develop/deployment.yaml -n dev1
    # - name: Cleanup
    #   if: always()
    #   run: |
    #     rm -rf /home/ubuntu/actions-runner/_work/*
