name: Deploy to Kubernetes

on:
 workflow_dispatch:
  inputs:
    ENVIRONMENT:
      type: choice
      description: select target environment
      options: [DEV, ST, SIT, UAT, PROD, DR]
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG6 }}
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: check the content
        run: |
           ls -la $GITHUB_WORKSPACE
           #ls -la /home/runner/work/devops-repo
           #ls -la /home/runner/work/devops-repo/devops-repo

      - name: Download Artifacts into Dev 
        run: |
         ssh ${{ secrets.REMOTE_HOST }} 'pwd'
         cd "$(pwd)"
         ls -la 
         scp -o StrictHostKeyChecking=no "$(pwd)"/deployment1.yaml ${{ secrets.REMOTE_HOST }}:~/
         ls -la ~/
         kubectl apply -f deployment1.yaml
         
      # - name: Copy manifests to server
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #       host: ${{ secrets.REMOTE_HOST }}
      #       username: ${{ secrets.REMOTE_USERNAME }}
      #       #key: ${{ secrets.SSH_PRIVATE_KEY }}
      #       port: 22
      #       source: "${GITHUB_WORKSPACE}"         # local path in repo
      #       #source: "./k8s/*"         # local path in repo
      #       target: "/home/${{ secrets.REMOTE_USERNAME }}/k8s"   # remote path

      # Install kubectl (latest stable release)
      # - name: Install kubectl
      #   uses: azure/setup-kubectl@v4
      #   with:
      #      version: 'v1.31.0' # or 'latest'


      # Write kubeconfig from secret into a file
      # - name: Set up kubeconfig
      #   run: |
      #     echo "${{secrets.KUBE_CONFIG6}}" > ${{ github.workspace }}/kubeconfig.yaml
      #     echo "${{secrets.KUBE_CONFIG6}}" > $HOME/.kube/config
          # mkdir -p $HOME/.kube
          # sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          # sudo chown $(id -u):$(id -g) $HOME/.kube/config

      # Apply manifests
      # - name: Deploy manifests
      #   run: |
      #     kubectl apply -f deployment1.yaml -n dev1 --validate=false --insecure-skip-tls-verify=true
        
