name: k8s workflow
on:
 workflow_dispatch:
  inputs:
    ENVIRONMENT:
      type: choice
      description: select target environment
      options: [DEV, ST, SIT, UAT, PROD, DR]

jobs:
  deploying-to-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repository
      run: |
       cd ..
       git clone https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/venuakula-bigdata/develop.git
       
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
          version: 'latest'
    - name: Set up kubeconfig
      run: |
       mkdir -p $HOME/.kube
       echo "${KUBECONFIG}" > $HOME/.kube/config
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
    - name: Debug cluster info
      run: kubectl cluster-info
    - name: Test kubectl
      run: kubectl get nodes
    - name: deploying to k8s
      run: |
       ls -la $GITHUB_WORKSPACE
       ls -la /home/runner/work/devops-repo
       ls -la /home/runner/work/devops-repo/develop
       kubectl apply -f /home/runner/work/devops-repo/develop/deployment.yaml -n dev1
       env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
