name: k8s workflow demo
on:
 workflow_dispatch:
  inputs:
    ENVIRONMENT:
      type: choice
      description: select target environment
      options: [DEV, ST, SIT, UAT, PROD, DR]

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG2 }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: pwd
        run: |
         pwd

      # - name: Clone private repository
      #   run: |
      #    cd ..
      #    git clone https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/venuakula-bigdata/develop.git
      #    pwd
      #    ls -la $GITHUB_WORKSPACE
      #    ls -la /home/runner/work/devops-repo
      #    ls -la /home/runner/work/devops-repo/develop
      #    cd devops-repo/develop
      #    cp deployment.yml /home/runner/work/devops-repo/devops-repo/

      - name: Deploy Manifest
        uses: actions-hub/kubectl@master
        with:
          args: apply -f deployment1.yaml -n dev1 --validate=false --insecure-skip-tls-verify=true
